-- Test oracle for VC-PIVOT-001: EAV Pivot Views for External Queries
-- Opens the pipeline DB and queries actual pivot views generated by the engine.
-- Traces to: HLR-STOR-006

return function(actual_doc, helpers)
    -- Sanity: pipeline produced output
    if not actual_doc or #actual_doc.blocks < 1 then
        return false, "Pipeline produced no output"
    end

    -- Open the pipeline database
    local sqlite = require("lsqlite3")
    if not helpers.db_file then
        return false, "helpers.db_file not provided by runner"
    end

    local db = sqlite.open(helpers.db_file)
    if not db then
        return false, "Failed to open pipeline DB: " .. helpers.db_file
    end

    local errors = {}
    local function err(msg) table.insert(errors, msg) end
    local function assert_eq(actual, expected, label)
        if actual ~= expected then
            err(string.format("%s: expected %s, got %s",
                label, tostring(expected), tostring(actual)))
        end
    end
    local function assert_nil(actual, label)
        if actual ~= nil then
            err(string.format("%s: expected nil, got %s", label, tostring(actual)))
        end
    end
    local function assert_not_nil(actual, label)
        if actual == nil then
            err(string.format("%s: expected non-nil value", label))
        end
    end

    -- Helper: query rows from the DB
    local function query(sql)
        local rows = {}
        for row in db:nrows(sql) do
            table.insert(rows, row)
        end
        return rows
    end

    -- Helper: check view exists
    local function view_exists(name)
        local rows = query(string.format(
            "SELECT name FROM sqlite_master WHERE type='view' AND name='%s'", name))
        return #rows == 1
    end

    -- ================================================================
    -- TC-01: HLR pivot view exists and has correct row count
    -- Columns: priority (ENUM), rationale (XHTML) — directly owned by HLR
    -- Note: status is inherited from TRACEABLE, NOT in HLR pivot view
    -- ================================================================
    if not view_exists("view_hlr_objects") then
        err("TC-01: view_hlr_objects does not exist")
    else
        local hlrs = query("SELECT * FROM view_hlr_objects ORDER BY pid")
        assert_eq(#hlrs, 3, "TC-01: view_hlr_objects row count")

        -- ================================================================
        -- TC-02: ENUM column (priority) resolves to human-readable key
        -- ================================================================
        assert_eq(hlrs[1].priority, "High", "TC-02: HLR-001 priority enum key")

        -- ================================================================
        -- TC-03: XHTML column (rationale) via string_value
        -- ================================================================
        assert_not_nil(hlrs[1].rationale, "TC-03: HLR-001 rationale not nil")

        -- ================================================================
        -- TC-04: Core columns present and correct
        -- ================================================================
        assert_not_nil(hlrs[1].id, "TC-04a: core column id")
        assert_not_nil(hlrs[1].specification_ref, "TC-04b: core column specification_ref")
        assert_eq(hlrs[1].pid, "HLR-001", "TC-04c: core column pid")
        assert_eq(hlrs[1].title_text, "Fully Attributed Requirement",
            "TC-04d: core column title_text")
        assert_not_nil(hlrs[1].from_file, "TC-04e: core column from_file")
        assert_eq(hlrs[1].level, 2, "TC-04f: core column level")
        assert_not_nil(hlrs[1].label, "TC-04g: core column label")

        -- ================================================================
        -- TC-05: Sparse attributes produce NULL for missing values
        -- HLR-002 only has status (inherited, not in view), so all HLR attrs NULL
        -- ================================================================
        assert_nil(hlrs[2].priority, "TC-05a: HLR-002 missing priority is NULL")
        assert_nil(hlrs[2].rationale, "TC-05b: HLR-002 missing rationale is NULL")

        -- ================================================================
        -- TC-06: Object with NO attributes has all attr columns NULL
        -- ================================================================
        assert_eq(hlrs[3].pid, "HLR-003", "TC-06a: HLR-003 exists in view")
        assert_nil(hlrs[3].priority, "TC-06b: HLR-003 no-attr priority NULL")
        assert_nil(hlrs[3].rationale, "TC-06c: HLR-003 no-attr rationale NULL")
        assert_eq(hlrs[3].title_text, "Bare Requirement",
            "TC-06d: HLR-003 core columns survive")

        -- ================================================================
        -- TC-07: WHERE filter on ENUM column
        -- ================================================================
        local high = query("SELECT * FROM view_hlr_objects WHERE priority = 'High'")
        assert_eq(#high, 1, "TC-07a: WHERE priority='High' returns 1 row")
        assert_eq(high[1].pid, "HLR-001", "TC-07b: filtered row is HLR-001")
    end

    -- ================================================================
    -- TC-08: NFR pivot view with STRING + multiple ENUMs
    -- Columns: category (ENUM), metric (STRING), priority (ENUM), rationale (XHTML)
    -- ================================================================
    if not view_exists("view_nfr_objects") then
        err("TC-08: view_nfr_objects does not exist")
    else
        local nfrs = query("SELECT * FROM view_nfr_objects ORDER BY pid")
        assert_eq(#nfrs, 2, "TC-08a: view_nfr_objects row count")
        assert_eq(nfrs[1].category, "Performance", "TC-08b: NFR-001 category enum")
        assert_eq(nfrs[1].priority, "Mid", "TC-08c: NFR-001 priority enum")
        assert_eq(nfrs[1].metric, "< 100ms p99 latency", "TC-08d: NFR-001 metric string")
        assert_eq(nfrs[2].category, "Security", "TC-08e: NFR-002 category enum")
        assert_nil(nfrs[2].metric, "TC-08f: NFR-002 missing metric is NULL")
        assert_nil(nfrs[2].priority, "TC-08g: NFR-002 missing priority is NULL")

        -- WHERE filter on ENUM column
        local perf = query("SELECT * FROM view_nfr_objects WHERE category = 'Performance'")
        assert_eq(#perf, 1, "TC-08h: WHERE on category returns 1 row")

        -- WHERE filter on STRING column
        local metric = query("SELECT * FROM view_nfr_objects WHERE metric IS NOT NULL")
        assert_eq(#metric, 1, "TC-08i: WHERE on metric IS NOT NULL returns 1 row")
    end

    -- ================================================================
    -- TC-09: VC pivot view with ENUM + XHTML attributes
    -- VC overrides status from TRACEABLE, so status IS in the VC pivot view
    -- ================================================================
    if not view_exists("view_vc_objects") then
        err("TC-09: view_vc_objects does not exist")
    else
        local vcs = query("SELECT * FROM view_vc_objects ORDER BY pid")
        local found = false
        for _, vc in ipairs(vcs) do
            if vc.pid == "VC-PIVOT-SMOKE" then
                found = true
                assert_eq(vc.verification_method, "Test",
                    "TC-09a: VC verification_method enum")
                assert_not_nil(vc.objective, "TC-09b: VC objective XHTML present")
                assert_eq(vc.status, "Approved", "TC-09c: VC status enum")
            end
        end
        if not found then
            err("TC-09d: VC-PIVOT-SMOKE not found in view_vc_objects")
        end
    end

    -- ================================================================
    -- TC-10: TR pivot view with result ENUM + STRING attributes
    -- ================================================================
    if not view_exists("view_tr_objects") then
        err("TC-10: view_tr_objects does not exist")
    else
        local trs = query("SELECT * FROM view_tr_objects ORDER BY pid")
        local found = false
        for _, tr in ipairs(trs) do
            if tr.pid == "TR-001" then
                found = true
                assert_eq(tr.result, "Pass", "TC-10a: TR result enum")
                assert_eq(tr.execution_date, "2025-06-15",
                    "TC-10b: TR execution_date string")
                assert_eq(tr.executed_by, "ci-runner",
                    "TC-10c: TR executed_by string")
                assert_eq(tr.test_file,
                    "tests/e2e/pivot/vc_033_01_eav_views.md",
                    "TC-10d: TR test_file string")
            end
        end
        if not found then
            err("TC-10e: TR-001 not found in view_tr_objects")
        end
    end

    -- ================================================================
    -- TC-11: Different types produce separate views with different columns
    -- HLR has priority column; NFR has category column (not in HLR)
    -- ================================================================
    if view_exists("view_hlr_objects") then
        local hlr1 = query("SELECT * FROM view_hlr_objects LIMIT 1")
        if #hlr1 > 0 then
            assert_nil(hlr1[1].category, "TC-11a: HLR view has no 'category' column")
            assert_nil(hlr1[1].metric, "TC-11b: HLR view has no 'metric' column")
        end
    end

    -- ================================================================
    -- TC-12: SECTION type gets a pivot view with description column
    -- ================================================================
    if view_exists("view_section_objects") then
        local sections = query("SELECT * FROM view_section_objects")
        local found = false
        for _, s in ipairs(sections) do
            if s.title_text and s.title_text:find("Additional Context", 1, true) then
                found = true
            end
        end
        if not found then
            err("TC-12: 'Additional Context' section not found in view_section_objects")
        end
    end

    -- ================================================================
    -- TC-13: Multiple pivot views generated (one per non-composite type)
    -- ================================================================
    local views = query(
        "SELECT name FROM sqlite_master WHERE type='view' AND name LIKE 'view_%_objects' ORDER BY name")
    if #views < 3 then
        err(string.format("TC-13a: Expected at least 3 pivot views, found %d", #views))
    end
    for _, v in ipairs(views) do
        if not v.name:match("^view_[a-z]+_objects$") then
            err(string.format("TC-13b: View name '%s' doesn't match convention", v.name))
        end
    end

    -- ================================================================
    -- TC-14: Verify at least HLR, NFR, VC, TR views all present
    -- ================================================================
    local expected_views = { "view_hlr_objects", "view_nfr_objects",
                             "view_vc_objects", "view_tr_objects" }
    for _, name in ipairs(expected_views) do
        if not view_exists(name) then
            err(string.format("TC-14: Expected view '%s' not found", name))
        end
    end

    -- Cleanup
    db:close()

    -- Report
    if #errors > 0 then
        return false, "EAV pivot view validation failed (" .. #errors .. " errors):\n  - "
            .. table.concat(errors, "\n  - ")
    end
    return true, nil
end
